! Generated by utils/mechanism_contract.py from src/lib/Lib_ChemMech/mechanism_contract.json: DO NOT EDIT BY HAND.
!
! Mechanism contract: for every name hooked in Assign_Mechanism, the species slots (name and
! elemental composition, in routine order) and the number of reactions per table type that the
! compiled routine expects. check_mechanism_contract compares the record with what
! read_idealgas_thermo / read_chemistry loaded:
!  - the routine species must be the first ns_r loaded species, in order (PREFIX semantics);
!    species loaded after them are accepted and stay inert (the callers zero the source term);
!  - a slot matches by elemental composition, and by name too for a generated routine or where
!    two slots of the routine share a composition; a hand-written routine accepts a calibrated
!    species under another name with the same composition (e.g. H2ONassini for H2O);
!  - without composition data (no composition.txt) the molecular weight of phase.txt is compared
!    with the one of the expected composition (tolerance 0.05 kg/kmol) instead;
!  - the reaction counts per table type (Arrhenius, falloff-Troe, falloff-Lindemann) must match.
! The records are published in src/lib/Lib_ChemMech/mechanism_contract.json (format in
! docs/user/chemistry_routines.md): a table writer can check its files against them.
module FLINT_Lib_Chemistry_contract
  implicit none
  private
  public :: mechanism_expectation, check_mechanism_contract, canonical_composition
  integer, parameter, public :: contract_str_len = 32
  integer, parameter, public :: n_contract_cases = 26
contains

  !> Expectation record of a hooked mechanism name; found = .false. for a name that falls back to general.
  subroutine mechanism_expectation(name, found, routine, generated, ns_r, nrc_r, sp_name, sp_comp, sp_wm)
    implicit none
    character(*), intent(in) :: name
    logical, intent(out) :: found, generated
    character(contract_str_len), intent(out) :: routine
    integer, intent(out) :: ns_r, nrc_r(3)   ! Arrhenius, falloff-Troe, falloff-Lindemann
    character(contract_str_len), allocatable, intent(out) :: sp_name(:), sp_comp(:)
    real(8), allocatable, intent(out) :: sp_wm(:)   ! molecular weight of each slot [kg/kmol]

    found = .true.; generated = .false.; routine = ''; ns_r = 0; nrc_r = 0
    select case (name)
    case ('WD')
      routine = 'WD'; generated = .false.; ns_r = 5
      nrc_r = [3, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'CH4', &
        'O2', &
        'CO2', &
        'H2O', &
        'CO']
      sp_comp = [character(contract_str_len) :: &
        'C1H4', &
        'O2', &
        'C1O2', &
        'H2O1', &
        'C1O1']
      sp_wm = [real(8) :: &
        16.0430d0, &
        31.9980d0, &
        44.0090d0, &
        18.0150d0, &
        28.0100d0]
    case ('JLR-Nasuti')
      routine = 'JLR'; generated = .false.; ns_r = 9
      nrc_r = [7, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'O2', &
        'CH4', &
        'H2O', &
        'CO', &
        'CO2', &
        'H2', &
        'H', &
        'O', &
        'OH']
      sp_comp = [character(contract_str_len) :: &
        'O2', &
        'C1H4', &
        'H2O1', &
        'C1O1', &
        'C1O2', &
        'H2', &
        'H1', &
        'O1', &
        'H1O1']
      sp_wm = [real(8) :: &
        31.9980d0, &
        16.0430d0, &
        18.0150d0, &
        28.0100d0, &
        44.0090d0, &
        2.0160d0, &
        1.0080d0, &
        15.9990d0, &
        17.0070d0]
    case ('Frassoldati')
      routine = 'Frassoldati'; generated = .false.; ns_r = 9
      nrc_r = [6, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'O2', &
        'CH4', &
        'H2O', &
        'CO', &
        'CO2', &
        'H2', &
        'H', &
        'O', &
        'OH']
      sp_comp = [character(contract_str_len) :: &
        'O2', &
        'C1H4', &
        'H2O1', &
        'C1O1', &
        'C1O2', &
        'H2', &
        'H1', &
        'O1', &
        'H1O1']
      sp_wm = [real(8) :: &
        31.9980d0, &
        16.0430d0, &
        18.0150d0, &
        28.0100d0, &
        44.0090d0, &
        2.0160d0, &
        1.0080d0, &
        15.9990d0, &
        17.0070d0]
    case ('Smooke')
      routine = 'smooke'; generated = .true.; ns_r = 16
      nrc_r = [35, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'CH4', &
        'H2', &
        'O2', &
        'O', &
        'H', &
        'OH', &
        'HO2', &
        'H2O2', &
        'H2O', &
        'CO', &
        'CH3', &
        'CH2O', &
        'HCO', &
        'CH3O', &
        'CO2', &
        'N2']
      sp_comp = [character(contract_str_len) :: &
        'C1H4', &
        'H2', &
        'O2', &
        'O1', &
        'H1', &
        'H1O1', &
        'H1O2', &
        'H2O2', &
        'H2O1', &
        'C1O1', &
        'C1H3', &
        'C1H2O1', &
        'C1H1O1', &
        'C1H3O1', &
        'C1O2', &
        'N2']
      sp_wm = [real(8) :: &
        16.0430d0, &
        2.0160d0, &
        31.9980d0, &
        15.9990d0, &
        1.0080d0, &
        17.0070d0, &
        33.0060d0, &
        34.0140d0, &
        18.0150d0, &
        28.0100d0, &
        15.0350d0, &
        30.0260d0, &
        29.0180d0, &
        31.0340d0, &
        44.0090d0, &
        28.0140d0]
    case ('CORIA-CNRS')
      routine = 'coria'; generated = .true.; ns_r = 17
      nrc_r = [40, 4, 0]
      sp_name = [character(contract_str_len) :: &
        'H2', &
        'H', &
        'O', &
        'O2', &
        'OH', &
        'H2O', &
        'HO2', &
        'CH3', &
        'CH4', &
        'CO', &
        'CO2', &
        'H2O2', &
        'HCO', &
        'CH2O', &
        'CH3O', &
        'C2H6', &
        'CH3O2']
      sp_comp = [character(contract_str_len) :: &
        'H2', &
        'H1', &
        'O1', &
        'O2', &
        'H1O1', &
        'H2O1', &
        'H1O2', &
        'C1H3', &
        'C1H4', &
        'C1O1', &
        'C1O2', &
        'H2O2', &
        'C1H1O1', &
        'C1H2O1', &
        'C1H3O1', &
        'C2H6', &
        'C1H3O2']
      sp_wm = [real(8) :: &
        2.0160d0, &
        1.0080d0, &
        15.9990d0, &
        31.9980d0, &
        17.0070d0, &
        18.0150d0, &
        33.0060d0, &
        15.0350d0, &
        16.0430d0, &
        28.0100d0, &
        44.0090d0, &
        34.0140d0, &
        29.0180d0, &
        30.0260d0, &
        31.0340d0, &
        30.0700d0, &
        47.0330d0]
    case ('TSR-CDF-13')
      routine = 'TSRCDF13'; generated = .true.; ns_r = 13
      nrc_r = [43, 3, 0]
      sp_name = [character(contract_str_len) :: &
        'OH', &
        'HO2', &
        'H2', &
        'CO2', &
        'CO', &
        'H2O', &
        'CH4', &
        'H', &
        'CH3', &
        'O2', &
        'CH2O', &
        'HCO', &
        'O']
      sp_comp = [character(contract_str_len) :: &
        'H1O1', &
        'H1O2', &
        'H2', &
        'C1O2', &
        'C1O1', &
        'H2O1', &
        'C1H4', &
        'H1', &
        'C1H3', &
        'O2', &
        'C1H2O1', &
        'C1H1O1', &
        'O1']
      sp_wm = [real(8) :: &
        17.0070d0, &
        33.0060d0, &
        2.0160d0, &
        44.0090d0, &
        28.0100d0, &
        18.0150d0, &
        16.0430d0, &
        1.0080d0, &
        15.0350d0, &
        31.9980d0, &
        30.0260d0, &
        29.0180d0, &
        15.9990d0]
    case ('TSR-GP-24')
      routine = 'TSRGP24'; generated = .true.; ns_r = 24
      nrc_r = [102, 8, 0]
      sp_name = [character(contract_str_len) :: &
        'HO2', &
        'H2O2', &
        'CO', &
        'OH', &
        'H2', &
        'HCO', &
        'CH3O', &
        'CH2(S)', &
        'H', &
        'O', &
        'C3H2', &
        'CH3', &
        'C2H2', &
        'CH2O', &
        'C3H3', &
        'C2H', &
        'H2O', &
        'CH3O2', &
        'O2', &
        'CH2', &
        'C2H6', &
        'CH4', &
        'HCO2', &
        'CO2']
      sp_comp = [character(contract_str_len) :: &
        'H1O2', &
        'H2O2', &
        'C1O1', &
        'H1O1', &
        'H2', &
        'C1H1O1', &
        'C1H3O1', &
        'C1H2', &
        'H1', &
        'O1', &
        'C3H2', &
        'C1H3', &
        'C2H2', &
        'C1H2O1', &
        'C3H3', &
        'C2H1', &
        'H2O1', &
        'C1H3O2', &
        'O2', &
        'C1H2', &
        'C2H6', &
        'C1H4', &
        'C1H1O2', &
        'C1O2']
      sp_wm = [real(8) :: &
        33.0060d0, &
        34.0140d0, &
        28.0100d0, &
        17.0070d0, &
        2.0160d0, &
        29.0180d0, &
        31.0340d0, &
        14.0270d0, &
        1.0080d0, &
        15.9990d0, &
        38.0490d0, &
        15.0350d0, &
        26.0380d0, &
        30.0260d0, &
        39.0570d0, &
        25.0300d0, &
        18.0150d0, &
        47.0330d0, &
        31.9980d0, &
        14.0270d0, &
        30.0700d0, &
        16.0430d0, &
        45.0170d0, &
        44.0090d0]
    case ('TSR-Rich-31')
      routine = 'TSRRich31'; generated = .true.; ns_r = 31
      nrc_r = [185, 12, 0]
      sp_name = [character(contract_str_len) :: &
        'IC3H7CO', &
        'CH2CHO', &
        'H', &
        'CH4', &
        'C2H2', &
        'C3H3', &
        'C2H3', &
        'O', &
        'H2O2', &
        'CO', &
        'CH2O', &
        'C2H6', &
        'CH2CO', &
        'IC3H7', &
        'H2O', &
        'O2', &
        'CH2(S)', &
        'HCO', &
        'CH3', &
        'H2', &
        'CH3CO', &
        'C3H6O1-3', &
        'C2H4O1-2', &
        'C2H3O1-2', &
        'HO2', &
        'C2H4', &
        'CH', &
        'OH', &
        'C2H5', &
        'CH2', &
        'CO2']
      sp_comp = [character(contract_str_len) :: &
        'C4H7O1', &
        'C2H3O1', &
        'H1', &
        'C1H4', &
        'C2H2', &
        'C3H3', &
        'C2H3', &
        'O1', &
        'H2O2', &
        'C1O1', &
        'C1H2O1', &
        'C2H6', &
        'C2H2O1', &
        'C3H7', &
        'H2O1', &
        'O2', &
        'C1H2', &
        'C1H1O1', &
        'C1H3', &
        'H2', &
        'C2H3O1', &
        'C3H6O1', &
        'C2H4O1', &
        'C2H3O1', &
        'H1O2', &
        'C2H4', &
        'C1H1', &
        'H1O1', &
        'C2H5', &
        'C1H2', &
        'C1O2']
      sp_wm = [real(8) :: &
        71.0990d0, &
        43.0450d0, &
        1.0080d0, &
        16.0430d0, &
        26.0380d0, &
        39.0570d0, &
        27.0460d0, &
        15.9990d0, &
        34.0140d0, &
        28.0100d0, &
        30.0260d0, &
        30.0700d0, &
        42.0370d0, &
        43.0890d0, &
        18.0150d0, &
        31.9980d0, &
        14.0270d0, &
        29.0180d0, &
        15.0350d0, &
        2.0160d0, &
        43.0450d0, &
        58.0800d0, &
        44.0530d0, &
        43.0450d0, &
        33.0060d0, &
        28.0540d0, &
        13.0190d0, &
        17.0070d0, &
        29.0620d0, &
        14.0270d0, &
        44.0090d0]
    case ('ZK')
      routine = 'ZK'; generated = .true.; ns_r = 25
      nrc_r = [45, 6, 0]
      sp_name = [character(contract_str_len) :: &
        'AR', &
        'N2', &
        'H2', &
        'H', &
        'O', &
        'O2', &
        'OH', &
        'H2O', &
        'HO2', &
        'H2O2', &
        'CO', &
        'CO2', &
        'C', &
        'CH', &
        'CH2', &
        'CH3', &
        'CH4', &
        'HCO', &
        'CH2O', &
        'CH3O', &
        'C2H3', &
        'C2H4', &
        'C2H5', &
        'C2H6', &
        'CH3O2']
      sp_comp = [character(contract_str_len) :: &
        'Ar1', &
        'N2', &
        'H2', &
        'H1', &
        'O1', &
        'O2', &
        'H1O1', &
        'H2O1', &
        'H1O2', &
        'H2O2', &
        'C1O1', &
        'C1O2', &
        'C1', &
        'C1H1', &
        'C1H2', &
        'C1H3', &
        'C1H4', &
        'C1H1O1', &
        'C1H2O1', &
        'C1H3O1', &
        'C2H3', &
        'C2H4', &
        'C2H5', &
        'C2H6', &
        'C1H3O2']
      sp_wm = [real(8) :: &
        39.9480d0, &
        28.0140d0, &
        2.0160d0, &
        1.0080d0, &
        15.9990d0, &
        31.9980d0, &
        17.0070d0, &
        18.0150d0, &
        33.0060d0, &
        34.0140d0, &
        28.0100d0, &
        44.0090d0, &
        12.0110d0, &
        13.0190d0, &
        14.0270d0, &
        15.0350d0, &
        16.0430d0, &
        29.0180d0, &
        30.0260d0, &
        31.0340d0, &
        27.0460d0, &
        28.0540d0, &
        29.0620d0, &
        30.0700d0, &
        47.0330d0]
    case ('CoronettiC4H6')
      routine = 'Coronetti'; generated = .false.; ns_r = 9
      nrc_r = [6, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'O2', &
        'C4H6', &
        'H2O', &
        'CO', &
        'CO2', &
        'H2', &
        'O', &
        'H', &
        'OH']
      sp_comp = [character(contract_str_len) :: &
        'O2', &
        'C4H6', &
        'H2O1', &
        'C1O1', &
        'C1O2', &
        'H2', &
        'O1', &
        'H1', &
        'H1O1']
      sp_wm = [real(8) :: &
        31.9980d0, &
        54.0920d0, &
        18.0150d0, &
        28.0100d0, &
        44.0090d0, &
        2.0160d0, &
        15.9990d0, &
        1.0080d0, &
        17.0070d0]
    case ('CKJLR-10sp')
      routine = 'CKJLR10sp'; generated = .false.; ns_r = 10
      nrc_r = [8, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'O2', &
        'C2H4', &
        'H2O', &
        'CO', &
        'CO2', &
        'H2', &
        'H', &
        'O', &
        'OH', &
        'C12H24']
      sp_comp = [character(contract_str_len) :: &
        'O2', &
        'C2H4', &
        'H2O1', &
        'C1O1', &
        'C1O2', &
        'H2', &
        'H1', &
        'O1', &
        'H1O1', &
        'C12H24']
      sp_wm = [real(8) :: &
        31.9980d0, &
        28.0540d0, &
        18.0150d0, &
        28.0100d0, &
        44.0090d0, &
        2.0160d0, &
        1.0080d0, &
        15.9990d0, &
        17.0070d0, &
        168.3240d0]
    case ('Singh')
      routine = 'singh'; generated = .false.; ns_r = 9
      nrc_r = [10, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'H', &
        'C2H4', &
        'OH', &
        'CO', &
        'CO2', &
        'H2', &
        'H2O', &
        'O2', &
        'O']
      sp_comp = [character(contract_str_len) :: &
        'H1', &
        'C2H4', &
        'H1O1', &
        'C1O1', &
        'C1O2', &
        'H2', &
        'H2O1', &
        'O2', &
        'O1']
      sp_wm = [real(8) :: &
        1.0080d0, &
        28.0540d0, &
        17.0070d0, &
        28.0100d0, &
        44.0090d0, &
        2.0160d0, &
        18.0150d0, &
        31.9980d0, &
        15.9990d0]
    case ('Singh-WC32')
      routine = 'Singh_WC32'; generated = .false.; ns_r = 10
      nrc_r = [11, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'H', &
        'C2H4', &
        'OH', &
        'CO', &
        'CO2', &
        'H2', &
        'H2O', &
        'O2', &
        'O', &
        'C32H66']
      sp_comp = [character(contract_str_len) :: &
        'H1', &
        'C2H4', &
        'H1O1', &
        'C1O1', &
        'C1O2', &
        'H2', &
        'H2O1', &
        'O2', &
        'O1', &
        'C32H66']
      sp_wm = [real(8) :: &
        1.0080d0, &
        28.0540d0, &
        17.0070d0, &
        28.0100d0, &
        44.0090d0, &
        2.0160d0, &
        18.0150d0, &
        31.9980d0, &
        15.9990d0, &
        450.8800d0]
    case ('Frolov')
      routine = 'Frolov'; generated = .false.; ns_r = 3
      nrc_r = [1, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'O2', &
        'H2O', &
        'H2']
      sp_comp = [character(contract_str_len) :: &
        'O2', &
        'H2O1', &
        'H2']
      sp_wm = [real(8) :: &
        31.9980d0, &
        18.0150d0, &
        2.0160d0]
    case ('Nassini')
      routine = 'Nassini_4'; generated = .false.; ns_r = 3
      nrc_r = [2, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'O2', &
        'H2O', &
        'H2']
      sp_comp = [character(contract_str_len) :: &
        'O2', &
        'H2O1', &
        'H2']
      sp_wm = [real(8) :: &
        31.9980d0, &
        18.0150d0, &
        2.0160d0]
    case ('Troyes')
      routine = 'troyes'; generated = .true.; ns_r = 12
      nrc_r = [17, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'H', &
        'O2', &
        'OH', &
        'O', &
        'H2O', &
        'H2', &
        'CO', &
        'CO2', &
        'CL', &
        'CL2', &
        'HCL', &
        'N2']
      sp_comp = [character(contract_str_len) :: &
        'H1', &
        'O2', &
        'H1O1', &
        'O1', &
        'H2O1', &
        'H2', &
        'C1O1', &
        'C1O2', &
        'Cl1', &
        'Cl2', &
        'Cl1H1', &
        'N2']
      sp_wm = [real(8) :: &
        1.0080d0, &
        31.9980d0, &
        17.0070d0, &
        15.9990d0, &
        18.0150d0, &
        2.0160d0, &
        28.0100d0, &
        44.0090d0, &
        35.4500d0, &
        70.9000d0, &
        36.4580d0, &
        28.0140d0]
    case ('Ecker')
      routine = 'ecker'; generated = .true.; ns_r = 14
      nrc_r = [28, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'H2', &
        'O2', &
        'HO2', &
        'H', &
        'O', &
        'OH', &
        'H2O', &
        'H2O2', &
        'CO', &
        'CO2', &
        'HCL', &
        'CL2', &
        'CL', &
        'N2']
      sp_comp = [character(contract_str_len) :: &
        'H2', &
        'O2', &
        'H1O2', &
        'H1', &
        'O1', &
        'H1O1', &
        'H2O1', &
        'H2O2', &
        'C1O1', &
        'C1O2', &
        'Cl1H1', &
        'Cl2', &
        'Cl1', &
        'N2']
      sp_wm = [real(8) :: &
        2.0160d0, &
        31.9980d0, &
        33.0060d0, &
        1.0080d0, &
        15.9990d0, &
        17.0070d0, &
        18.0150d0, &
        34.0140d0, &
        28.0100d0, &
        44.0090d0, &
        36.4580d0, &
        70.9000d0, &
        35.4500d0, &
        28.0140d0]
    case ('Cross')
      routine = 'cross'; generated = .true.; ns_r = 19
      nrc_r = [33, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'C2H2', &
        'CH2O', &
        'CH2', &
        'CH3', &
        'CH4', &
        'CO', &
        'CO2', &
        'CL', &
        'CL2', &
        'CLO', &
        'H', &
        'H2', &
        'H2O', &
        'HCN', &
        'HCO', &
        'HCL', &
        'N2', &
        'O', &
        'OH']
      sp_comp = [character(contract_str_len) :: &
        'C2H2', &
        'C1H2O1', &
        'C1H2', &
        'C1H3', &
        'C1H4', &
        'C1O1', &
        'C1O2', &
        'Cl1', &
        'Cl2', &
        'Cl1O1', &
        'H1', &
        'H2', &
        'H2O1', &
        'C1H1N1', &
        'C1H1O1', &
        'Cl1H1', &
        'N2', &
        'O1', &
        'H1O1']
      sp_wm = [real(8) :: &
        26.0380d0, &
        30.0260d0, &
        14.0270d0, &
        15.0350d0, &
        16.0430d0, &
        28.0100d0, &
        44.0090d0, &
        35.4500d0, &
        70.9000d0, &
        51.4490d0, &
        1.0080d0, &
        2.0160d0, &
        18.0150d0, &
        27.0260d0, &
        29.0180d0, &
        36.4580d0, &
        28.0140d0, &
        15.9990d0, &
        17.0070d0]
    case ('Pelucchi')
      routine = 'pelucchi'; generated = .true.; ns_r = 25
      nrc_r = [97, 2, 4]
      sp_name = [character(contract_str_len) :: &
        'HCL', &
        'CL2', &
        'CL', &
        'CLO', &
        'HOCL', &
        'CLOO', &
        'OCLO', &
        'CLCHO', &
        'CLCO', &
        'CH2O', &
        'HE', &
        'AR', &
        'N2', &
        'O2', &
        'H2', &
        'H2O', &
        'H2O2', &
        'CO', &
        'CO2', &
        'O3', &
        'O', &
        'H', &
        'OH', &
        'HO2', &
        'HCO']
      sp_comp = [character(contract_str_len) :: &
        'Cl1H1', &
        'Cl2', &
        'Cl1', &
        'Cl1O1', &
        'Cl1H1O1', &
        'Cl1O2', &
        'Cl1O2', &
        'C1Cl1H1O1', &
        'C1Cl1O1', &
        'C1H2O1', &
        'He1', &
        'Ar1', &
        'N2', &
        'O2', &
        'H2', &
        'H2O1', &
        'H2O2', &
        'C1O1', &
        'C1O2', &
        'O3', &
        'O1', &
        'H1', &
        'H1O1', &
        'H1O2', &
        'C1H1O1']
      sp_wm = [real(8) :: &
        36.4580d0, &
        70.9000d0, &
        35.4500d0, &
        51.4490d0, &
        52.4570d0, &
        67.4480d0, &
        67.4480d0, &
        64.4680d0, &
        63.4600d0, &
        30.0260d0, &
        4.0026d0, &
        39.9480d0, &
        28.0140d0, &
        31.9980d0, &
        2.0160d0, &
        18.0150d0, &
        34.0140d0, &
        28.0100d0, &
        44.0090d0, &
        47.9970d0, &
        15.9990d0, &
        1.0080d0, &
        17.0070d0, &
        33.0060d0, &
        29.0180d0]
    case ('WD-Andersen')
      routine = 'Andersen'; generated = .false.; ns_r = 5
      nrc_r = [3, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'CH4', &
        'O2', &
        'CO2', &
        'H2O', &
        'CO']
      sp_comp = [character(contract_str_len) :: &
        'C1H4', &
        'O2', &
        'C1O2', &
        'H2O1', &
        'C1O1']
      sp_wm = [real(8) :: &
        16.0430d0, &
        31.9980d0, &
        44.0090d0, &
        18.0150d0, &
        28.0100d0]
    case ('OSK')
      routine = 'OSK'; generated = .false.; ns_r = 4
      nrc_r = [1, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'O2', &
        'CH4', &
        'H2O', &
        'CO2']
      sp_comp = [character(contract_str_len) :: &
        'O2', &
        'C1H4', &
        'H2O1', &
        'C1O2']
      sp_wm = [real(8) :: &
        31.9980d0, &
        16.0430d0, &
        18.0150d0, &
        44.0090d0]
    case ('ONERA-7')
      routine = 'ONERA_7'; generated = .true.; ns_r = 7
      nrc_r = [14, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'O2', &
        'H2O', &
        'H2', &
        'H', &
        'O', &
        'OH', &
        'N2']
      sp_comp = [character(contract_str_len) :: &
        'O2', &
        'H2O1', &
        'H2', &
        'H1', &
        'O1', &
        'H1O1', &
        'N2']
      sp_wm = [real(8) :: &
        31.9980d0, &
        18.0150d0, &
        2.0160d0, &
        1.0080d0, &
        15.9990d0, &
        17.0070d0, &
        28.0140d0]
    case ('Frolov_nopressure')
      routine = 'Frolov_nopressure'; generated = .false.; ns_r = 4
      nrc_r = [1, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'O2', &
        'H2O', &
        'H2', &
        'N2']
      sp_comp = [character(contract_str_len) :: &
        'O2', &
        'H2O1', &
        'H2', &
        'N2']
      sp_wm = [real(8) :: &
        31.9980d0, &
        18.0150d0, &
        2.0160d0, &
        28.0140d0]
    case ('SanDiego')
      routine = 'sandiego20161214'; generated = .true.; ns_r = 57
      nrc_r = [245, 23, 0]
      sp_name = [character(contract_str_len) :: &
        'N2', &
        'AR', &
        'HE', &
        'H', &
        'O2', &
        'OH', &
        'O', &
        'H2', &
        'H2O', &
        'HO2', &
        'H2O2', &
        'CO', &
        'CO2', &
        'HCO', &
        'CH3', &
        'CH4', &
        'CH2O', &
        'T-CH2', &
        'S-CH2', &
        'C2H4', &
        'CH3O', &
        'C2H5', &
        'C2H6', &
        'CH', &
        'C2H2', &
        'C2H4OOH', &
        'OC2H3OOH', &
        'C2H3', &
        'CH2CHO', &
        'C2H4O', &
        'HCCO', &
        'CH2CO', &
        'C2H', &
        'CH2OH', &
        'CH3OH', &
        'CH3CHO', &
        'CH3CO', &
        'C2H5OH', &
        'CH2CH2OH', &
        'CH3CHOH', &
        'CH3CH2O', &
        'C3H4', &
        'C3H3', &
        'C3H5', &
        'C3H6', &
        'C3H8', &
        'I-C3H7', &
        'N-C3H7', &
        'C3H6OOH', &
        'OC3H5OOH', &
        'C4H10', &
        'PC4H9', &
        'SC4H9', &
        'C4H8', &
        'SC4H9O2', &
        'C4H8OOH1-3', &
        'NC4KET13']
      sp_comp = [character(contract_str_len) :: &
        'N2', &
        'Ar1', &
        'He1', &
        'H1', &
        'O2', &
        'H1O1', &
        'O1', &
        'H2', &
        'H2O1', &
        'H1O2', &
        'H2O2', &
        'C1O1', &
        'C1O2', &
        'C1H1O1', &
        'C1H3', &
        'C1H4', &
        'C1H2O1', &
        'C1H2', &
        'C1H2', &
        'C2H4', &
        'C1H3O1', &
        'C2H5', &
        'C2H6', &
        'C1H1', &
        'C2H2', &
        'C2H5O2', &
        'C2H4O3', &
        'C2H3', &
        'C2H3O1', &
        'C2H4O1', &
        'C2H1O1', &
        'C2H2O1', &
        'C2H1', &
        'C1H3O1', &
        'C1H4O1', &
        'C2H4O1', &
        'C2H3O1', &
        'C2H6O1', &
        'C2H5O1', &
        'C2H5O1', &
        'C2H5O1', &
        'C3H4', &
        'C3H3', &
        'C3H5', &
        'C3H6', &
        'C3H8', &
        'C3H7', &
        'C3H7', &
        'C3H7O2', &
        'C3H6O3', &
        'C4H10', &
        'C4H9', &
        'C4H9', &
        'C4H8', &
        'C4H9O2', &
        'C4H9O2', &
        'C4H8O3']
      sp_wm = [real(8) :: &
        28.0140d0, &
        39.9480d0, &
        4.0026d0, &
        1.0080d0, &
        31.9980d0, &
        17.0070d0, &
        15.9990d0, &
        2.0160d0, &
        18.0150d0, &
        33.0060d0, &
        34.0140d0, &
        28.0100d0, &
        44.0090d0, &
        29.0180d0, &
        15.0350d0, &
        16.0430d0, &
        30.0260d0, &
        14.0270d0, &
        14.0270d0, &
        28.0540d0, &
        31.0340d0, &
        29.0620d0, &
        30.0700d0, &
        13.0190d0, &
        26.0380d0, &
        61.0600d0, &
        76.0510d0, &
        27.0460d0, &
        43.0450d0, &
        44.0530d0, &
        41.0290d0, &
        42.0370d0, &
        25.0300d0, &
        31.0340d0, &
        32.0420d0, &
        44.0530d0, &
        43.0450d0, &
        46.0690d0, &
        45.0610d0, &
        45.0610d0, &
        45.0610d0, &
        40.0650d0, &
        39.0570d0, &
        41.0730d0, &
        42.0810d0, &
        44.0970d0, &
        43.0890d0, &
        43.0890d0, &
        75.0870d0, &
        90.0780d0, &
        58.1240d0, &
        57.1160d0, &
        57.1160d0, &
        56.1080d0, &
        89.1140d0, &
        89.1140d0, &
        104.1050d0]
    case ('FFCMy-12')
      routine = 'FFCMy_12'; generated = .true.; ns_r = 13
      nrc_r = [34, 3, 1]
      sp_name = [character(contract_str_len) :: &
        'H2', &
        'H', &
        'O2', &
        'O', &
        'OH', &
        'HO2', &
        'H2O', &
        'CH3', &
        'CH4', &
        'CO', &
        'CO2', &
        'CH2O', &
        'N2']
      sp_comp = [character(contract_str_len) :: &
        'H2', &
        'H1', &
        'O2', &
        'O1', &
        'H1O1', &
        'H1O2', &
        'H2O1', &
        'C1H3', &
        'C1H4', &
        'C1O1', &
        'C1O2', &
        'C1H2O1', &
        'N2']
      sp_wm = [real(8) :: &
        2.0160d0, &
        1.0080d0, &
        31.9980d0, &
        15.9990d0, &
        17.0070d0, &
        33.0060d0, &
        18.0150d0, &
        15.0350d0, &
        16.0430d0, &
        28.0100d0, &
        44.0090d0, &
        30.0260d0, &
        28.0140d0]
    case ('Gerlinger-9')
      routine = 'Gerlinger9'; generated = .true.; ns_r = 9
      nrc_r = [19, 0, 0]
      sp_name = [character(contract_str_len) :: &
        'N2', &
        'O2', &
        'H2', &
        'H2O', &
        'OH', &
        'O', &
        'H', &
        'HO2', &
        'H2O2']
      sp_comp = [character(contract_str_len) :: &
        'N2', &
        'O2', &
        'H2', &
        'H2O1', &
        'H1O1', &
        'O1', &
        'H1', &
        'H1O2', &
        'H2O2']
      sp_wm = [real(8) :: &
        28.0140d0, &
        31.9980d0, &
        2.0160d0, &
        18.0150d0, &
        17.0070d0, &
        15.9990d0, &
        1.0080d0, &
        33.0060d0, &
        34.0140d0]
    case default
      found = .false.
      allocate(sp_name(0), sp_comp(0), sp_wm(0))
    end select
  end subroutine mechanism_expectation

  !> Elemental composition as a string: element symbols in standard case (CL -> Cl) and ASCII
  !> order, each followed by its integer count (H2O -> 'H2O1', CH4 -> 'C1H4'); elements with a
  !> zero count are omitted.
  function canonical_composition(comp, els) result(str)
    implicit none
    real(8), intent(in) :: comp(:)
    character(*), intent(in) :: els(:)
    character(contract_str_len) :: str
    character(contract_str_len) :: sym(size(els))
    integer :: i, j, k, ne, idx(size(els)), n
    character(16) :: num
    ne = size(els)
    do i = 1, ne
      sym(i) = element_symbol(els(i))
      idx(i) = i
    enddo
    ! insertion sort of the element symbols (ne is small)
    do i = 2, ne
      k = idx(i); j = i - 1
      do while (j >= 1)
        if (.not. (trim(sym(idx(j))) > trim(sym(k)))) exit
        idx(j+1) = idx(j); j = j - 1
      enddo
      idx(j+1) = k
    enddo
    str = ''
    do i = 1, ne
      n = nint(comp(idx(i)))
      if (n == 0) cycle
      write(num, '(I0)') n
      str = trim(str)//trim(sym(idx(i)))//trim(num)
    enddo
  end function canonical_composition

  !> Element symbol in standard case: first letter upper, the rest lower ('CL' -> 'Cl').
  function element_symbol(el) result(sym)
    implicit none
    character(*), intent(in) :: el
    character(contract_str_len) :: sym
    integer :: i, c
    sym = trim(adjustl(el))
    do i = 1, len_trim(sym)
      c = iachar(sym(i:i))
      if (i == 1) then
        if (c >= iachar('a') .and. c <= iachar('z')) sym(i:i) = achar(c - 32)
      else
        if (c >= iachar('A') .and. c <= iachar('Z')) sym(i:i) = achar(c + 32)
      endif
    enddo
  end function element_symbol

  !> Compare the expectation record of `name` with the loaded species (FLINT_Lib_Thermodynamic) and
  !> reaction counts (FLINT_Lib_Chemistry_data). ok = .true. for a name that is not hooked (nothing to
  !> check) and for a match; on a mismatch both lists are printed and ok = .false.
  !> The check needs the species (read_idealgas_thermo) and the rate tables (read_chemistry). When they
  !> are not loaded yet: with the argument `loaded` present, loaded = .false. and ok = .true. with
  !> nothing printed (the caller checks again later: Assign_Mechanism defers the check to the first
  !> chemistry call); without it, an [ERROR] line and ok = .false.
  subroutine check_mechanism_contract(name, ok, loaded)
    use FLINT_Lib_Thermodynamic, only: ns, species_names, species_composition, elements_names, wm_tab
    use FLINT_Lib_Chemistry_data, only: nrc_arrh, nrc_troe, nrc_lindemann, rxn_type
    use iso_fortran_env, only: error_unit
    implicit none
    character(*), intent(in) :: name
    logical, intent(out) :: ok
    logical, intent(out), optional :: loaded
    character(len=512) :: line
    logical :: found, generated, have_comp, comp_ok, name_ok, need_name
    character(contract_str_len) :: routine
    character(contract_str_len), allocatable :: sp_name(:), sp_comp(:), ld_comp(:)
    real(8), allocatable :: sp_wm(:)
    real(8), parameter :: wm_tol = 0.05d0   ! kg/kmol
    integer :: ns_r, nrc_r(3), i, nbad, nrc_l(3)

    ok = .true.
    if (present(loaded)) loaded = .true.
    call mechanism_expectation(name, found, routine, generated, ns_r, nrc_r, sp_name, sp_comp, sp_wm)
    if (.not. found) return
    if (.not. (allocated(species_names) .and. allocated(rxn_type))) then
      if (present(loaded)) then
        loaded = .false.
        return
      endif
      call say('[ERROR] FLINT mechanism '//trim(name)//' (routine '//trim(routine)// &
        '): the species and rate tables are not loaded (read_idealgas_thermo, read_chemistry)')
      ok = .false.
      return
    endif
    have_comp = allocated(species_composition) .and. allocated(elements_names)
    if (have_comp) have_comp = (size(species_composition, 2) == ns) .and. &
                               (size(species_composition, 1) == size(elements_names))
    allocate(ld_comp(ns))
    ld_comp = ''
    if (have_comp) then
      do i = 1, ns
        ld_comp(i) = canonical_composition(species_composition(:,i), elements_names)
      enddo
    else
      do i = 1, ns
        write(ld_comp(i), '(A,F0.3)') 'M=', wm_tab(i)
      enddo
    endif
    nbad = 0
    if (ns < ns_r) nbad = nbad + 1
    do i = 1, min(ns, ns_r)
      if (have_comp) then
        comp_ok = (trim(ld_comp(i)) == trim(sp_comp(i)))
      else
        ! no composition.txt (INPUT folders written before the table writer wrote it): the
        ! molecular weight of phase.txt, which the routine itself uses, stands in for the
        ! composition, and the loaded name must begin with the slot name (H2OCalib for H2O):
        ! the weight alone cannot tell CO from N2 or C2H4 (28.010, 28.014, 28.054 kg/kmol)
        comp_ok = (abs(wm_tab(i) - sp_wm(i)) <= wm_tol) .and. &
                  (index(upper(species_names(i)), trim(upper(sp_name(i)))) == 1)
      endif
      need_name = generated .or. (count(sp_comp == sp_comp(i)) > 1)
      name_ok = (.not. need_name) .or. (trim(species_names(i)) == trim(sp_name(i)))
      if (.not. (comp_ok .and. name_ok)) nbad = nbad + 1
    enddo
    nrc_l = [nrc_arrh, nrc_troe, nrc_lindemann]
    if (any(nrc_l /= nrc_r)) nbad = nbad + 1
    if (nbad > 0) then
      ! the refusal and its two lists go to standard output AND to the error unit: a solver
      ! that splits the channels sees the whole message next to the error stop
      call say('[ERROR] FLINT mechanism '//trim(name)//' (routine '//trim(routine)// &
        '): the loaded species/reactions do not match the compiled routine')
      write(line,'(A,I0,A)') '  expected: ', ns_r, ' species (slot name [composition]), then any inert species:'
      call say(line)
      do i = 1, ns_r
        write(line,'(A,I0,A,F0.3,A)') '    ', i, ' '//trim(sp_name(i))//' ['//trim(sp_comp(i))//' M=', sp_wm(i), ']'
        call say(line)
      enddo
      write(line,'(A,I0,A)') '  loaded  : ', ns, ' species:'
      call say(line)
      do i = 1, ns
        write(line,'(A,I0,A)') '    ', i, ' '//trim(species_names(i))//' ['//trim(ld_comp(i))//']'
        call say(line)
      enddo
      write(line,'(A,3(I0,A))') '  expected reactions (Arrhenius, falloff-Troe, falloff-Lindemann): ', &
        nrc_r(1), ' ', nrc_r(2), ' ', nrc_r(3), ''
      call say(line)
      write(line,'(A,3(I0,A))') '  loaded   reactions (Arrhenius, falloff-Troe, falloff-Lindemann): ', &
        nrc_l(1), ' ', nrc_l(2), ' ', nrc_l(3), ''
      call say(line)
      if (.not. have_comp) call say('  (no composition data loaded: slots compared by molecular weight,' // &
        ' tolerance 0.05 kg/kmol, and the loaded name must begin with the slot name)')
      ok = .false.
    else if (ns > ns_r) then
      write(*,'(A,I0,A)') '[INFO] FLINT mechanism '//trim(name)//': ', ns - ns_r, &
        ' species after the routine slots are inert: '//trim(list_names(ns_r+1, ns))
    endif
  contains
    subroutine say(text)
      character(*), intent(in) :: text
      write(*,'(A)') trim(text)
      write(error_unit,'(A)') trim(text)
    end subroutine say
    pure function upper(str) result(u)
      character(*), intent(in) :: str
      character(len=len(str)) :: u
      integer :: k, c
      u = str
      do k = 1, len(str)
        c = iachar(str(k:k))
        if (c >= iachar('a') .and. c <= iachar('z')) u(k:k) = achar(c - 32)
      enddo
    end function upper
    function list_names(i1, i2) result(str)
      integer, intent(in) :: i1, i2
      character(len=256) :: str
      integer :: k
      str = ''
      do k = i1, min(i2, i1 + 11)
        str = trim(str)//' '//trim(species_names(k))
      enddo
      if (i2 > i1 + 11) str = trim(str)//' ...'
    end function list_names
  end subroutine check_mechanism_contract

end module FLINT_Lib_Chemistry_contract
