#!/usr/bin/env python3
"""Generate src/lib/Lib_Chemistry_contract.f90 from src/lib/Lib_ChemMech/mechanism_contract.json.

The JSON records, for every name hooked in Assign_Mechanism, what the compiled routine expects:
the species slots (name + elemental composition) and the number of reactions per table type
(Arrhenius, falloff-Troe, falloff-Lindemann). The generated module returns that record
(mechanism_expectation) and compares it with the data loaded by read_idealgas_thermo /
read_chemistry (check_mechanism_contract); Assign_Mechanism refuses a hooked name whose loaded
data does not match. Run from the repository root:
    python3 utils/mechanism_contract.py            # writes src/lib/Lib_Chemistry_contract.f90
    python3 utils/mechanism_contract.py --check    # exit 1 (and a diff) if the committed module
                                                   # is not the output of this generator, or if the
                                                   # fingerprints, n_reactions or zeroes_omegadot of
                                                   # the JSON are not the ones of the sources
    python3 utils/mechanism_contract.py --fingerprints   # (re)write those fields into the JSON
The Fortran text after the case records (canonical_composition, element_symbol,
check_mechanism_contract) is kept here verbatim: change it here and regenerate.
"""
import json, os, sys, difflib, collections
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, 'src', 'lib', 'Lib_ChemMech', 'mechanism_contract.json')
dst = os.path.join(root, 'src', 'lib', 'Lib_Chemistry_contract.f90')
C = json.load(open(src), object_pairs_hook=collections.OrderedDict)

def symbol(el):
    """element symbol in standard case (CL -> Cl): composition.txt files may carry upper-case symbols"""
    return el[:1].upper() + el[1:].lower()

def canonical(comp):
    """elements in ASCII order, each followed by its integer count: {'H':2,'O':1} -> 'H2O1'"""
    return ''.join('%s%d' % (el, int(round(float(n)))) for el, n in sorted((symbol(e), n) for e, n in comp.items()) if int(round(float(n))) != 0)

# standard atomic weights [kg/kmol] of the elements that occur in the hooked routines (Cantera's
# phase.txt weights differ from these sums by < 1e-3)
ATOMIC_WEIGHTS = {'H': 1.008, 'C': 12.011, 'N': 14.007, 'O': 15.999, 'Ar': 39.948, 'He': 4.002602, 'Ne': 20.1797,
                  'Cl': 35.45, 'F': 18.998403, 'S': 32.06, 'Si': 28.085, 'Br': 79.904, 'Na': 22.98977, 'K': 39.0983, 'Al': 26.9815}

def molw(comp):
    """molecular weight [kg/kmol] from the elemental composition (unknown element -> KeyError)"""
    return sum(ATOMIC_WEIGHTS[symbol(el)] * float(n) for el, n in comp.items())

def fstr(s):
    return "'" + s.replace("'", "''") + "'"

L = []
L.append('! Generated by utils/mechanism_contract.py from src/lib/Lib_ChemMech/mechanism_contract.json: DO NOT EDIT BY HAND.')
L.append('!')
L.append('! Mechanism contract: for every name hooked in Assign_Mechanism, the species slots (name and')
L.append('! elemental composition, in routine order) and the number of reactions per table type that the')
L.append('! compiled routine expects. check_mechanism_contract compares the record with what')
L.append('! read_idealgas_thermo / read_chemistry loaded:')
L.append('!  - the routine species must be the first ns_r loaded species, in order (PREFIX semantics);')
L.append('!    species loaded after them are accepted and stay inert (the callers zero the source term);')
L.append('!  - a slot matches by elemental composition, and by name too for a generated routine or where')
L.append('!    two slots of the routine share a composition; a hand-written routine accepts a calibrated')
L.append('!    species under another name with the same composition (e.g. H2ONassini for H2O);')
L.append('!  - without composition data (no composition.txt) the molecular weight of phase.txt is compared')
L.append('!    with the one of the expected composition (tolerance 0.05 kg/kmol) instead;')
L.append('!  - the reaction counts per table type (Arrhenius, falloff-Troe, falloff-Lindemann) must match.')
L.append('! The records are published in src/lib/Lib_ChemMech/mechanism_contract.json (format in')
L.append('! docs/user/chemistry_routines.md): a table writer can check its files against them.')
L.append('module FLINT_Lib_Chemistry_contract')
L.append('  implicit none')
L.append('  private')
L.append('  public :: mechanism_expectation, check_mechanism_contract, canonical_composition')
L.append('  integer, parameter, public :: contract_str_len = 32')
L.append('  integer, parameter, public :: n_contract_cases = %d' % len(C['cases']))
L.append('contains')
L.append('')
L.append('  !> Expectation record of a hooked mechanism name; found = .false. for a name that falls back to general.')
L.append('  subroutine mechanism_expectation(name, found, routine, generated, ns_r, nrc_r, sp_name, sp_comp, sp_wm)')
L.append('    implicit none')
L.append('    character(*), intent(in) :: name')
L.append('    logical, intent(out) :: found, generated')
L.append('    character(contract_str_len), intent(out) :: routine')
L.append('    integer, intent(out) :: ns_r, nrc_r(3)   ! Arrhenius, falloff-Troe, falloff-Lindemann')
L.append('    character(contract_str_len), allocatable, intent(out) :: sp_name(:), sp_comp(:)')
L.append('    real(8), allocatable, intent(out) :: sp_wm(:)   ! molecular weight of each slot [kg/kmol]')
L.append('')
L.append('    found = .true.; generated = .false.; routine = \'\'; ns_r = 0; nrc_r = 0')
L.append('    select case (name)')
for name, c in C['cases'].items():
    sp = c['species']
    assert sp is not None and len(sp) == c['ns'], name
    L.append('    case (%s)' % fstr(name))
    L.append('      routine = %s; generated = %s; ns_r = %d' % (fstr(c['routine']), '.true.' if c['kind'] == 'generated' else '.false.', c['ns']))
    L.append('      nrc_r = [%d, %d, %d]' % (c['nrc']['arrhenius'], c['nrc']['troe'], c['nrc']['lindemann']))
    L.append('      sp_name = [character(contract_str_len) :: &')
    for i, s in enumerate(sp):
        L.append('        %s%s' % (fstr(s['name']), ', &' if i + 1 < len(sp) else ']'))
    L.append('      sp_comp = [character(contract_str_len) :: &')
    for i, s in enumerate(sp):
        L.append('        %s%s' % (fstr(canonical(s['composition'])), ', &' if i + 1 < len(sp) else ']'))
    L.append('      sp_wm = [real(8) :: &')
    for i, s in enumerate(sp):
        L.append('        %.4fd0%s' % (molw(s['composition']), ', &' if i + 1 < len(sp) else ']'))
L.append('    case default')
L.append('      found = .false.')
L.append('      allocate(sp_name(0), sp_comp(0), sp_wm(0))')
L.append('    end select')
L.append('  end subroutine mechanism_expectation')
L.append('')
L.append(r'''  !> Elemental composition as a string: element symbols in standard case (CL -> Cl) and ASCII
  !> order, each followed by its integer count (H2O -> 'H2O1', CH4 -> 'C1H4'); elements with a
  !> zero count are omitted.
  function canonical_composition(comp, els) result(str)
    implicit none
    real(8), intent(in) :: comp(:)
    character(*), intent(in) :: els(:)
    character(contract_str_len) :: str
    character(contract_str_len) :: sym(size(els))
    integer :: i, j, k, ne, idx(size(els)), n
    character(16) :: num
    ne = size(els)
    do i = 1, ne
      sym(i) = element_symbol(els(i))
      idx(i) = i
    enddo
    ! insertion sort of the element symbols (ne is small)
    do i = 2, ne
      k = idx(i); j = i - 1
      do while (j >= 1)
        if (.not. (trim(sym(idx(j))) > trim(sym(k)))) exit
        idx(j+1) = idx(j); j = j - 1
      enddo
      idx(j+1) = k
    enddo
    str = ''
    do i = 1, ne
      n = nint(comp(idx(i)))
      if (n == 0) cycle
      write(num, '(I0)') n
      str = trim(str)//trim(sym(idx(i)))//trim(num)
    enddo
  end function canonical_composition

  !> Element symbol in standard case: first letter upper, the rest lower ('CL' -> 'Cl').
  function element_symbol(el) result(sym)
    implicit none
    character(*), intent(in) :: el
    character(contract_str_len) :: sym
    integer :: i, c
    sym = trim(adjustl(el))
    do i = 1, len_trim(sym)
      c = iachar(sym(i:i))
      if (i == 1) then
        if (c >= iachar('a') .and. c <= iachar('z')) sym(i:i) = achar(c - 32)
      else
        if (c >= iachar('A') .and. c <= iachar('Z')) sym(i:i) = achar(c + 32)
      endif
    enddo
  end function element_symbol

  !> Compare the expectation record of `name` with the loaded species (FLINT_Lib_Thermodynamic) and
  !> reaction counts (FLINT_Lib_Chemistry_data). ok = .true. for a name that is not hooked (nothing to
  !> check) and for a match; on a mismatch both lists are printed and ok = .false.
  !> The check needs the species (read_idealgas_thermo) and the rate tables (read_chemistry). When they
  !> are not loaded yet: with the argument `loaded` present, loaded = .false. and ok = .true. with
  !> nothing printed (the caller checks again later: Assign_Mechanism defers the check to the first
  !> chemistry call); without it, an [ERROR] line and ok = .false.
  subroutine check_mechanism_contract(name, ok, loaded)
    use FLINT_Lib_Thermodynamic, only: ns, species_names, species_composition, elements_names, wm_tab
    use FLINT_Lib_Chemistry_data, only: nrc_arrh, nrc_troe, nrc_lindemann, rxn_type
    use iso_fortran_env, only: error_unit
    implicit none
    character(*), intent(in) :: name
    logical, intent(out) :: ok
    logical, intent(out), optional :: loaded
    character(len=512) :: line
    logical :: found, generated, have_comp, comp_ok, name_ok, need_name
    character(contract_str_len) :: routine
    character(contract_str_len), allocatable :: sp_name(:), sp_comp(:), ld_comp(:)
    real(8), allocatable :: sp_wm(:)
    real(8), parameter :: wm_tol = 0.05d0   ! kg/kmol
    integer :: ns_r, nrc_r(3), i, nbad, nrc_l(3)

    ok = .true.
    if (present(loaded)) loaded = .true.
    call mechanism_expectation(name, found, routine, generated, ns_r, nrc_r, sp_name, sp_comp, sp_wm)
    if (.not. found) return
    if (.not. (allocated(species_names) .and. allocated(rxn_type))) then
      if (present(loaded)) then
        loaded = .false.
        return
      endif
      call say('[ERROR] FLINT mechanism '//trim(name)//' (routine '//trim(routine)// &
        '): the species and rate tables are not loaded (read_idealgas_thermo, read_chemistry)')
      ok = .false.
      return
    endif
    have_comp = allocated(species_composition) .and. allocated(elements_names)
    if (have_comp) have_comp = (size(species_composition, 2) == ns) .and. &
                               (size(species_composition, 1) == size(elements_names))
    allocate(ld_comp(ns))
    ld_comp = ''
    if (have_comp) then
      do i = 1, ns
        ld_comp(i) = canonical_composition(species_composition(:,i), elements_names)
      enddo
    else
      do i = 1, ns
        write(ld_comp(i), '(A,F0.3)') 'M=', wm_tab(i)
      enddo
    endif
    nbad = 0
    if (ns < ns_r) nbad = nbad + 1
    do i = 1, min(ns, ns_r)
      if (have_comp) then
        comp_ok = (trim(ld_comp(i)) == trim(sp_comp(i)))
      else
        ! no composition.txt (INPUT folders written before the table writer wrote it): the
        ! molecular weight of phase.txt, which the routine itself uses, stands in for the
        ! composition, and the loaded name must begin with the slot name (H2OCalib for H2O):
        ! the weight alone cannot tell CO from N2 or C2H4 (28.010, 28.014, 28.054 kg/kmol)
        comp_ok = (abs(wm_tab(i) - sp_wm(i)) <= wm_tol) .and. &
                  (index(upper(species_names(i)), trim(upper(sp_name(i)))) == 1)
      endif
      need_name = generated .or. (count(sp_comp == sp_comp(i)) > 1)
      name_ok = (.not. need_name) .or. (trim(species_names(i)) == trim(sp_name(i)))
      if (.not. (comp_ok .and. name_ok)) nbad = nbad + 1
    enddo
    nrc_l = [nrc_arrh, nrc_troe, nrc_lindemann]
    if (any(nrc_l /= nrc_r)) nbad = nbad + 1
    if (nbad > 0) then
      ! the refusal and its two lists go to standard output AND to the error unit: a solver
      ! that splits the channels sees the whole message next to the error stop
      call say('[ERROR] FLINT mechanism '//trim(name)//' (routine '//trim(routine)// &
        '): the loaded species/reactions do not match the compiled routine')
      write(line,'(A,I0,A)') '  expected: ', ns_r, ' species (slot name [composition]), then any inert species:'
      call say(line)
      do i = 1, ns_r
        write(line,'(A,I0,A,F0.3,A)') '    ', i, ' '//trim(sp_name(i))//' ['//trim(sp_comp(i))//' M=', sp_wm(i), ']'
        call say(line)
      enddo
      write(line,'(A,I0,A)') '  loaded  : ', ns, ' species:'
      call say(line)
      do i = 1, ns
        write(line,'(A,I0,A)') '    ', i, ' '//trim(species_names(i))//' ['//trim(ld_comp(i))//']'
        call say(line)
      enddo
      write(line,'(A,3(I0,A))') '  expected reactions (Arrhenius, falloff-Troe, falloff-Lindemann): ', &
        nrc_r(1), ' ', nrc_r(2), ' ', nrc_r(3), ''
      call say(line)
      write(line,'(A,3(I0,A))') '  loaded   reactions (Arrhenius, falloff-Troe, falloff-Lindemann): ', &
        nrc_l(1), ' ', nrc_l(2), ' ', nrc_l(3), ''
      call say(line)
      if (.not. have_comp) call say('  (no composition data loaded: slots compared by molecular weight,' // &
        ' tolerance 0.05 kg/kmol, and the loaded name must begin with the slot name)')
      ok = .false.
    else if (ns > ns_r) then
      write(*,'(A,I0,A)') '[INFO] FLINT mechanism '//trim(name)//': ', ns - ns_r, &
        ' species after the routine slots are inert: '//trim(list_names(ns_r+1, ns))
    endif
  contains
    subroutine say(text)
      character(*), intent(in) :: text
      write(*,'(A)') trim(text)
      write(error_unit,'(A)') trim(text)
    end subroutine say
    pure function upper(str) result(u)
      character(*), intent(in) :: str
      character(len=len(str)) :: u
      integer :: k, c
      u = str
      do k = 1, len(str)
        c = iachar(str(k:k))
        if (c >= iachar('a') .and. c <= iachar('z')) u(k:k) = achar(c - 32)
      enddo
    end function upper
    function list_names(i1, i2) result(str)
      integer, intent(in) :: i1, i2
      character(len=256) :: str
      integer :: k
      str = ''
      do k = i1, min(i2, i1 + 11)
        str = trim(str)//' '//trim(species_names(k))
      enddo
      if (i2 > i1 + 11) str = trim(str)//' ...'
    end function list_names
  end subroutine check_mechanism_contract

end module FLINT_Lib_Chemistry_contract''')
text = '\n'.join(L) + '\n'
# ------------------------------------------------------------------------------------------------
# Reaction structure of the generated routines (format of utils/YTF.py: one '! reac n. <i>: <equation>'
# comment per reaction), read from the sources of src/lib: per reaction the rate table (class and index),
# the concentration factors per slot of the forward and backward products, the use of the third body and
# its efficiencies, and the stoichiometric rows of omegadot. It is recorded in the JSON as 'fingerprint'
# of every generated case, so that a table writer can check a mechanism file against a compiled routine
# reaction by reaction without reading the Fortran:
#     python3 utils/mechanism_contract.py --fingerprints   # (re)write the fingerprints into the JSON
#     python3 utils/mechanism_contract.py --check          # also fails when a recorded fingerprint differs
#                                                          # from the one computed from the sources
# ------------------------------------------------------------------------------------------------
import re, glob
from collections import Counter, OrderedDict

def statements(text):
    out, buf = [], ''
    for l in text.splitlines():
        s = l.rstrip()
        if buf:
            t = s.lstrip()
            if t.startswith('&'): t = t[1:]
            buf += t
        else: buf = s
        if buf.endswith('&'): buf = buf[:-1]; continue
        out.append(buf); buf = ''
    return out

def parse_dispatch(path):
    """case name -> (routine, jacobian or None), in file order"""
    cases, cur = OrderedDict(), None
    for line in open(path):
        s = line.strip()
        m = re.match(r"case\s*\((.*)\)\s*$", s, re.I)
        if m and 'default' not in s.lower():
            cur = re.findall(r"'([^']*)'", m.group(1)); continue
        if re.match(r"case\s+default", s, re.I): cur = None; continue
        m = re.match(r"chemistry_source\s*=>\s*(\w+)", s, re.I)
        if m and cur:
            for n in cur: cases[n] = {'routine': m.group(1), 'jacobian': None}
            continue
        m = re.match(r"chemistry_jacobian\s*=>\s*(\w+)", s, re.I)
        if m and cur and m.group(1).lower() != 'null()':
            for n in cur: cases[n]['jacobian'] = m.group(1)
    return cases

def load_routines(fdir):
    """name.lower() -> (name, file, body); sigs: name.lower() -> normalised dummy-argument list"""
    routines, sigs = {}, {}
    for f in sorted(glob.glob(os.path.join(fdir, '**', '*.f90'), recursive=True)):
        st = statements(open(f, errors='replace').read()); name = None; body = []
        for s in st:
            m = re.match(r"\s*subroutine\s+(\w+)\s*\((.*?)\)", s, re.I)
            if m: name = m.group(1); sigs[name.lower()] = re.sub(r"\s+", "", m.group(2)).lower(); body = []; continue
            if name and re.match(r"\s*end\s+subroutine", s, re.I):
                routines[name.lower()] = (name, os.path.basename(f), body); name = None; continue
            if name: body.append(s)
    return routines, sigs

def parse_M(expr):
    eff = {}
    ms = re.fullmatch(r"\s*sum\(coi\((\d+):(\d+)\)\)\s*", expr)
    if ms: return {i: 1.0 for i in range(int(ms.group(1)), int(ms.group(2)) + 1)}
    for term in expr.split('+'):
        term = term.strip()
        m = re.fullmatch(r"coi\((\d+)\)(?:\s*\*\s*([0-9.]+(?:[eEdD][+-]?\d+)?))?", term)
        m2 = re.fullmatch(r"([0-9.]+(?:[eEdD][+-]?\d+)?)\s*\*\s*coi\((\d+)\)", term)
        if m: eff[int(m.group(1))] = float((m.group(2) or '1').replace('d', 'e').replace('D', 'e'))
        elif m2: eff[int(m2.group(2))] = float(m2.group(1).replace('d', 'e').replace('D', 'e'))
        else: raise ValueError('unparsed third-body term: %r' % term)
    return eff

def group_eff(M):
    """{slot: eff} -> {"eff": [[value, [slots]]...]} (slots absent from M have efficiency 0)"""
    g = OrderedDict()
    for k, v in sorted(M.items()):
        if v != 0: g.setdefault(repr(v), []).append(k)   # a slot written with efficiency 0 (coi(k)*0.0) is absent: efficiency 0 and no entry are the same
    return [[float(v), s] for v, s in g.items()]

def parse_generated(body):
    R, om, curM, curk = OrderedDict(), OrderedDict(), None, None
    for s in body:
        t = s.strip()
        m = re.match(r"!\s*reac n\.\s*(\d+):\s*(.*)", t)
        if m: R.setdefault(int(m.group(1)), {})['eq'] = m.group(2).strip(); curM = None; curk = None; continue
        m = re.match(r"M\s*=\s*(.*)", t)
        if m: curM = parse_M(m.group(1)); continue
        m = re.match(r"k\s*=\s*f_k_(troe|lindemann)\s*\(\s*(\d+)\s*,", t, re.I)
        if m: curk = ['troe' if m.group(1).lower() == 'troe' else 'lindemann', int(m.group(2))]; continue
        m = re.match(r"prod([fb])\((\d+)\)\s*=\s*(.*)", t)
        if m:
            side, n, e = m.group(1), int(m.group(2)), m.group(3)
            mk = re.search(r"f_k([fb])\s*\(\s*(\d+)\s*,", e)
            if mk: tab = ['arrhenius', int(mk.group(2))]
            elif re.search(r"\bk\(\s*[12]\s*\)", e): tab = curk
            else: raise ValueError('reaction %d: unknown rate table in %r' % (n, e))
            fac = Counter(int(x) for x in re.findall(r"coi\((\d+)\)", e))
            r = R.setdefault(n, {})
            r[side] = OrderedDict([('tab', tab), ('fac', OrderedDict((str(k), v) for k, v in sorted(fac.items()))),
                                   ('usesM', bool(re.search(r"\*\s*M\b", e))), ('Meff', group_eff(curM) if curM is not None else None)])
            continue
        m = re.match(r"omegadot\((\d+)\)\s*=\s*(.*)", t)
        if m:
            i = int(m.group(1)); e = m.group(2); row = OrderedDict()
            for sg, a, b, n in re.findall(r"([+-]?)\(\s*([0-9.]+)\s*-\s*([0-9.]+)\s*\)\s*\*\s*\(\s*prodf\((\d+)\)", e):
                v = (float(a) - float(b)) * (-1 if sg == '-' else 1); row[str(n)] = row.get(str(n), 0) + v
            om[str(i)] = OrderedDict((k, v) for k, v in row.items() if abs(v) > 0)
    return R, om

zeroes = OrderedDict()   # case name -> the routine zeroes omegadot (computed by fingerprints())

def fingerprints():
    """{case name: fingerprint} of the generated cases of the JSON, computed from src/lib; errors (list)"""
    lib = os.path.join(root, 'src', 'lib')
    dispatch = parse_dispatch(os.path.join(lib, 'Lib_Chemistry_wdot.f90'))
    routines, _ = load_routines(lib)
    out, errors = OrderedDict(), []
    for name, c in C['cases'].items():
        rb = routines.get(c['routine'].lower())
        if rb is not None:   # every case: does the routine zero omegadot before its assignments (trailing species stay 0)?
            zeroes[name] = bool(re.search(r"omegadot\s*=\s*0", '\n'.join(t.split('!')[0] for t in rb[2])))
        if c.get('kind') != 'generated':
            continue
        d = dispatch.get(name)
        if d is None or d['routine'].lower() != c['routine'].lower():
            errors.append('case %s: Assign_Mechanism selects %s, the JSON records %s' % (name, d and d['routine'], c['routine'])); continue
        rname, rfile, body = routines.get(c['routine'].lower(), (None, None, None))
        if body is None:
            errors.append('case %s: routine %s not found in src/lib' % (name, c['routine'])); continue
        try:
            R, om = parse_generated(body)
        except ValueError as e:
            errors.append('case %s: %s' % (name, e)); continue
        narr = len(set(r['f']['tab'][1] for r in R.values() if r['f']['tab'][0] == 'arrhenius'))
        ntroe = len(set(tuple(r['f']['tab']) for r in R.values() if r['f']['tab'][0] == 'troe'))
        nlind = len(set(tuple(r['f']['tab']) for r in R.values() if r['f']['tab'][0] == 'lindemann'))
        if [narr, ntroe, nlind] != [c['nrc']['arrhenius'], c['nrc']['troe'], c['nrc']['lindemann']]:
            errors.append('case %s: the routine reads %d/%d/%d Arrhenius/Troe/Lindemann tables, the JSON records %s' % (name, narr, ntroe, nlind, dict(c['nrc'])))
        Mtab = []   # distinct third-body efficiency sets of the routine; the reactions refer to them by index
        for n in sorted(R):
            for side in ('f', 'b'):
                if side in R[n]:
                    me = R[n][side].pop('Meff')
                    if me is not None:
                        key = json.dumps(me)
                        if key not in [json.dumps(x) for x in Mtab]: Mtab.append(me)
                        R[n][side]['Mi'] = [json.dumps(x) for x in Mtab].index(key)
        out[name] = OrderedDict([('M', Mtab), ('reactions', OrderedDict((str(n), R[n]) for n in sorted(R))), ('omegadot', om)])
    return out, errors

def dump_contract(c):
    """the JSON text: indent 1, each fingerprint on one line (data for a checker, not for the eye)"""
    fps, cc = {}, json.loads(json.dumps(c), object_pairs_hook=collections.OrderedDict)
    for name, e in cc['cases'].items():
        if e.get('fingerprint') is not None:
            fps[name] = json.dumps(e['fingerprint'], separators=(',', ':')); e['fingerprint'] = '@@FP:%s@@' % name
    t = json.dumps(cc, indent=1)
    for name, f in fps.items():
        t = t.replace('"@@FP:%s@@"' % name, f)
    return t + '\n'

if '--fingerprints' in sys.argv[1:]:
    fp, errs = fingerprints()
    if errs:
        print('\n'.join('ERROR: ' + e for e in errs)); sys.exit(1)
    for name, z in zeroes.items():
        C['cases'][name]['zeroes_omegadot'] = z
    for name, f in fp.items():
        C['cases'][name]['n_reactions'] = len(f['reactions'])
        C['cases'][name]['fingerprint'] = f
    open(src, 'w').write(dump_contract(C))
    print('fingerprints written for %d generated cases into %s' % (len(fp), os.path.relpath(src, root)))
    sys.exit(0)

if '--check' in sys.argv[1:]:
    # the recorded fingerprints must be the ones computed from the sources
    fp, errs = fingerprints()
    for name, f in fp.items():
        if json.loads(json.dumps(C['cases'][name].get('fingerprint'))) != json.loads(json.dumps(f)):
            errs.append('case %s: the fingerprint in the JSON is not the one of the routine (run --fingerprints)' % name)
        if C['cases'][name].get('n_reactions') != len(f['reactions']):
            errs.append('case %s: n_reactions is %s in the JSON, the routine has %d reactions (run --fingerprints)' % (name, C['cases'][name].get('n_reactions'), len(f['reactions'])))
    for name, z in zeroes.items():
        if C['cases'][name].get('zeroes_omegadot') != z:
            errs.append('case %s: zeroes_omegadot is %s in the JSON, the routine %s omegadot (run --fingerprints)' % (name, C['cases'][name].get('zeroes_omegadot'), 'zeroes' if z else 'does not zero'))
    if errs:
        print('\n'.join('MISMATCH: ' + e for e in errs)); sys.exit(1)
    print('OK: the fingerprints of the %d generated cases are the ones of their routines' % len(fp))
    # equality test: the committed module must be the output of this generator
    cur = open(dst).read()
    if cur != text:
        sys.stdout.writelines(difflib.unified_diff(cur.splitlines(True), text.splitlines(True),
                                                   'committed ' + os.path.relpath(dst, root), 'generated'))
        print('MISMATCH: %s is not the output of utils/mechanism_contract.py' % os.path.relpath(dst, root))
        sys.exit(1)
    print('OK: %s is the output of utils/mechanism_contract.py (%d cases)' % (os.path.relpath(dst, root), len(C['cases'])))
    sys.exit(0)
open(dst, 'w').write(text)
print('written', dst, 'cases', len(C['cases']))
