#!/usr/bin/env python3
"""Generate src/lib/Lib_Chemistry_contract.f90 from src/lib/Lib_ChemMech/mechanism_contract.json.

The JSON records, for every name hooked in Assign_Mechanism, what the compiled routine expects:
the species slots (name + elemental composition) and the number of reactions per table type
(Arrhenius, falloff-Troe, falloff-Lindemann). The generated module returns that record
(mechanism_expectation) and compares it with the data loaded by read_idealgas_thermo /
read_chemistry (check_mechanism_contract); Assign_Mechanism refuses a hooked name whose loaded
data does not match. Run from the repository root:
    python3 utils/mechanism_contract.py            # writes src/lib/Lib_Chemistry_contract.f90
    python3 utils/mechanism_contract.py --check    # exit 1 (and a diff) if the committed module
                                                   # is not the output of this generator
The Fortran text after the case records (canonical_composition, element_symbol,
check_mechanism_contract) is kept here verbatim: change it here and regenerate.
"""
import json, os, sys, difflib, collections
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, 'src', 'lib', 'Lib_ChemMech', 'mechanism_contract.json')
dst = os.path.join(root, 'src', 'lib', 'Lib_Chemistry_contract.f90')
C = json.load(open(src), object_pairs_hook=collections.OrderedDict)

def symbol(el):
    """element symbol in standard case (CL -> Cl): composition.txt files may carry upper-case symbols"""
    return el[:1].upper() + el[1:].lower()

def canonical(comp):
    """elements in ASCII order, each followed by its integer count: {'H':2,'O':1} -> 'H2O1'"""
    return ''.join('%s%d' % (el, int(round(float(n)))) for el, n in sorted((symbol(e), n) for e, n in comp.items()) if int(round(float(n))) != 0)

# standard atomic weights [kg/kmol] of the elements that occur in the hooked routines (Cantera's
# phase.txt weights differ from these sums by < 1e-3)
ATOMIC_WEIGHTS = {'H': 1.008, 'C': 12.011, 'N': 14.007, 'O': 15.999, 'Ar': 39.948, 'He': 4.002602, 'Ne': 20.1797,
                  'Cl': 35.45, 'F': 18.998403, 'S': 32.06, 'Si': 28.085, 'Br': 79.904, 'Na': 22.98977, 'K': 39.0983, 'Al': 26.9815}

def molw(comp):
    """molecular weight [kg/kmol] from the elemental composition (unknown element -> KeyError)"""
    return sum(ATOMIC_WEIGHTS[symbol(el)] * float(n) for el, n in comp.items())

def fstr(s):
    return "'" + s.replace("'", "''") + "'"

L = []
L.append('! Generated by utils/mechanism_contract.py from src/lib/Lib_ChemMech/mechanism_contract.json: DO NOT EDIT BY HAND.')
L.append('!')
L.append('! Mechanism contract: for every name hooked in Assign_Mechanism, the species slots (name and')
L.append('! elemental composition, in routine order) and the number of reactions per table type that the')
L.append('! compiled routine expects. check_mechanism_contract compares the record with what')
L.append('! read_idealgas_thermo / read_chemistry loaded:')
L.append('!  - the routine species must be the first ns_r loaded species, in order (PREFIX semantics);')
L.append('!    species loaded after them are accepted and stay inert (the callers zero the source term);')
L.append('!  - a slot matches by elemental composition, and by name too for a generated routine or where')
L.append('!    two slots of the routine share a composition; a hand-written routine accepts a calibrated')
L.append('!    species under another name with the same composition (e.g. H2ONassini for H2O);')
L.append('!  - without composition data (no composition.txt) the molecular weight of phase.txt is compared')
L.append('!    with the one of the expected composition (tolerance 0.05 kg/kmol) instead;')
L.append('!  - the reaction counts per table type (Arrhenius, falloff-Troe, falloff-Lindemann) must match.')
L.append('! The records are published in src/lib/Lib_ChemMech/mechanism_contract.json (format in')
L.append('! docs/user/chemistry_routines.md): a table writer can check its files against them.')
L.append('module FLINT_Lib_Chemistry_contract')
L.append('  implicit none')
L.append('  private')
L.append('  public :: mechanism_expectation, check_mechanism_contract, canonical_composition')
L.append('  integer, parameter, public :: contract_str_len = 32')
L.append('  integer, parameter, public :: n_contract_cases = %d' % len(C['cases']))
L.append('contains')
L.append('')
L.append('  !> Expectation record of a hooked mechanism name; found = .false. for a name that falls back to general.')
L.append('  subroutine mechanism_expectation(name, found, routine, generated, ns_r, nrc_r, sp_name, sp_comp, sp_wm)')
L.append('    implicit none')
L.append('    character(*), intent(in) :: name')
L.append('    logical, intent(out) :: found, generated')
L.append('    character(contract_str_len), intent(out) :: routine')
L.append('    integer, intent(out) :: ns_r, nrc_r(3)   ! Arrhenius, falloff-Troe, falloff-Lindemann')
L.append('    character(contract_str_len), allocatable, intent(out) :: sp_name(:), sp_comp(:)')
L.append('    real(8), allocatable, intent(out) :: sp_wm(:)   ! molecular weight of each slot [kg/kmol]')
L.append('')
L.append('    found = .true.; generated = .false.; routine = \'\'; ns_r = 0; nrc_r = 0')
L.append('    select case (name)')
for name, c in C['cases'].items():
    sp = c['species']
    assert sp is not None and len(sp) == c['ns'], name
    L.append('    case (%s)' % fstr(name))
    L.append('      routine = %s; generated = %s; ns_r = %d' % (fstr(c['routine']), '.true.' if c['kind'] == 'generated' else '.false.', c['ns']))
    L.append('      nrc_r = [%d, %d, %d]' % (c['nrc']['arrhenius'], c['nrc']['troe'], c['nrc']['lindemann']))
    L.append('      sp_name = [character(contract_str_len) :: &')
    for i, s in enumerate(sp):
        L.append('        %s%s' % (fstr(s['name']), ', &' if i + 1 < len(sp) else ']'))
    L.append('      sp_comp = [character(contract_str_len) :: &')
    for i, s in enumerate(sp):
        L.append('        %s%s' % (fstr(canonical(s['composition'])), ', &' if i + 1 < len(sp) else ']'))
    L.append('      sp_wm = [real(8) :: &')
    for i, s in enumerate(sp):
        L.append('        %.4fd0%s' % (molw(s['composition']), ', &' if i + 1 < len(sp) else ']'))
L.append('    case default')
L.append('      found = .false.')
L.append('      allocate(sp_name(0), sp_comp(0), sp_wm(0))')
L.append('    end select')
L.append('  end subroutine mechanism_expectation')
L.append('')
L.append(r'''  !> Elemental composition as a string: element symbols in standard case (CL -> Cl) and ASCII
  !> order, each followed by its integer count (H2O -> 'H2O1', CH4 -> 'C1H4'); elements with a
  !> zero count are omitted.
  function canonical_composition(comp, els) result(str)
    implicit none
    real(8), intent(in) :: comp(:)
    character(*), intent(in) :: els(:)
    character(contract_str_len) :: str
    character(contract_str_len) :: sym(size(els))
    integer :: i, j, k, ne, idx(size(els)), n
    character(16) :: num
    ne = size(els)
    do i = 1, ne
      sym(i) = element_symbol(els(i))
      idx(i) = i
    enddo
    ! insertion sort of the element symbols (ne is small)
    do i = 2, ne
      k = idx(i); j = i - 1
      do while (j >= 1)
        if (.not. (trim(sym(idx(j))) > trim(sym(k)))) exit
        idx(j+1) = idx(j); j = j - 1
      enddo
      idx(j+1) = k
    enddo
    str = ''
    do i = 1, ne
      n = nint(comp(idx(i)))
      if (n == 0) cycle
      write(num, '(I0)') n
      str = trim(str)//trim(sym(idx(i)))//trim(num)
    enddo
  end function canonical_composition

  !> Element symbol in standard case: first letter upper, the rest lower ('CL' -> 'Cl').
  function element_symbol(el) result(sym)
    implicit none
    character(*), intent(in) :: el
    character(contract_str_len) :: sym
    integer :: i, c
    sym = trim(adjustl(el))
    do i = 1, len_trim(sym)
      c = iachar(sym(i:i))
      if (i == 1) then
        if (c >= iachar('a') .and. c <= iachar('z')) sym(i:i) = achar(c - 32)
      else
        if (c >= iachar('A') .and. c <= iachar('Z')) sym(i:i) = achar(c + 32)
      endif
    enddo
  end function element_symbol

  !> Compare the expectation record of `name` with the loaded species (FLINT_Lib_Thermodynamic) and
  !> reaction counts (FLINT_Lib_Chemistry_data). ok = .true. for a name that is not hooked (nothing to
  !> check) and for a match; on a mismatch both lists are printed and ok = .false.
  subroutine check_mechanism_contract(name, ok)
    use FLINT_Lib_Thermodynamic, only: ns, species_names, species_composition, elements_names, wm_tab
    use FLINT_Lib_Chemistry_data, only: nrc_arrh, nrc_troe, nrc_lindemann
    use iso_fortran_env, only: error_unit
    implicit none
    character(*), intent(in) :: name
    logical, intent(out) :: ok
    character(len=512) :: line
    logical :: found, generated, have_comp, comp_ok, name_ok, need_name
    character(contract_str_len) :: routine
    character(contract_str_len), allocatable :: sp_name(:), sp_comp(:), ld_comp(:)
    real(8), allocatable :: sp_wm(:)
    real(8), parameter :: wm_tol = 0.05d0   ! kg/kmol
    integer :: ns_r, nrc_r(3), i, nbad, nrc_l(3)

    ok = .true.
    call mechanism_expectation(name, found, routine, generated, ns_r, nrc_r, sp_name, sp_comp, sp_wm)
    if (.not. found) return
    if (.not. allocated(species_names)) then
      call say('[ERROR] FLINT mechanism '//trim(name)//' (routine '//trim(routine)// &
        '): species not loaded: call read_idealgas_thermo and read_chemistry before Assign_Mechanism')
      ok = .false.
      return
    endif
    have_comp = allocated(species_composition) .and. allocated(elements_names)
    if (have_comp) have_comp = (size(species_composition, 2) == ns) .and. &
                               (size(species_composition, 1) == size(elements_names))
    allocate(ld_comp(ns))
    ld_comp = ''
    if (have_comp) then
      do i = 1, ns
        ld_comp(i) = canonical_composition(species_composition(:,i), elements_names)
      enddo
    else
      do i = 1, ns
        write(ld_comp(i), '(A,F0.3)') 'M=', wm_tab(i)
      enddo
    endif
    nbad = 0
    if (ns < ns_r) nbad = nbad + 1
    do i = 1, min(ns, ns_r)
      if (have_comp) then
        comp_ok = (trim(ld_comp(i)) == trim(sp_comp(i)))
      else
        ! no composition.txt (INPUT folders written before the table writer wrote it): the
        ! molecular weight of phase.txt, which the routine itself uses, stands in for the
        ! composition, and the loaded name must begin with the slot name (H2OCalib for H2O):
        ! the weight alone cannot tell CO from N2 or C2H4 (28.010, 28.014, 28.054 kg/kmol)
        comp_ok = (abs(wm_tab(i) - sp_wm(i)) <= wm_tol) .and. &
                  (index(upper(species_names(i)), trim(upper(sp_name(i)))) == 1)
      endif
      need_name = generated .or. (count(sp_comp == sp_comp(i)) > 1)
      name_ok = (.not. need_name) .or. (trim(species_names(i)) == trim(sp_name(i)))
      if (.not. (comp_ok .and. name_ok)) nbad = nbad + 1
    enddo
    nrc_l = [nrc_arrh, nrc_troe, nrc_lindemann]
    if (any(nrc_l /= nrc_r)) nbad = nbad + 1
    if (nbad > 0) then
      ! the refusal and its two lists go to standard output AND to the error unit: a solver
      ! that splits the channels sees the whole message next to the error stop
      call say('[ERROR] FLINT mechanism '//trim(name)//' (routine '//trim(routine)// &
        '): the loaded species/reactions do not match the compiled routine')
      write(line,'(A,I0,A)') '  expected: ', ns_r, ' species (slot name [composition]), then any inert species:'
      call say(line)
      do i = 1, ns_r
        write(line,'(A,I0,A,F0.3,A)') '    ', i, ' '//trim(sp_name(i))//' ['//trim(sp_comp(i))//' M=', sp_wm(i), ']'
        call say(line)
      enddo
      write(line,'(A,I0,A)') '  loaded  : ', ns, ' species:'
      call say(line)
      do i = 1, ns
        write(line,'(A,I0,A)') '    ', i, ' '//trim(species_names(i))//' ['//trim(ld_comp(i))//']'
        call say(line)
      enddo
      write(line,'(A,3(I0,A))') '  expected reactions (Arrhenius, falloff-Troe, falloff-Lindemann): ', &
        nrc_r(1), ' ', nrc_r(2), ' ', nrc_r(3), ''
      call say(line)
      write(line,'(A,3(I0,A))') '  loaded   reactions (Arrhenius, falloff-Troe, falloff-Lindemann): ', &
        nrc_l(1), ' ', nrc_l(2), ' ', nrc_l(3), ''
      call say(line)
      if (.not. have_comp) call say('  (no composition data loaded: slots compared by molecular weight,' // &
        ' tolerance 0.05 kg/kmol, and the loaded name must begin with the slot name)')
      ok = .false.
    else if (ns > ns_r) then
      write(*,'(A,I0,A)') '[INFO] FLINT mechanism '//trim(name)//': ', ns - ns_r, &
        ' species after the routine slots are inert: '//trim(list_names(ns_r+1, ns))
    endif
  contains
    subroutine say(text)
      character(*), intent(in) :: text
      write(*,'(A)') trim(text)
      write(error_unit,'(A)') trim(text)
    end subroutine say
    pure function upper(str) result(u)
      character(*), intent(in) :: str
      character(len=len(str)) :: u
      integer :: k, c
      u = str
      do k = 1, len(str)
        c = iachar(str(k:k))
        if (c >= iachar('a') .and. c <= iachar('z')) u(k:k) = achar(c - 32)
      enddo
    end function upper
    function list_names(i1, i2) result(str)
      integer, intent(in) :: i1, i2
      character(len=256) :: str
      integer :: k
      str = ''
      do k = i1, min(i2, i1 + 11)
        str = trim(str)//' '//trim(species_names(k))
      enddo
      if (i2 > i1 + 11) str = trim(str)//' ...'
    end function list_names
  end subroutine check_mechanism_contract

end module FLINT_Lib_Chemistry_contract''')
text = '\n'.join(L) + '\n'
if '--check' in sys.argv[1:]:
    # equality test: the committed module must be the output of this generator
    cur = open(dst).read()
    if cur != text:
        sys.stdout.writelines(difflib.unified_diff(cur.splitlines(True), text.splitlines(True),
                                                   'committed ' + os.path.relpath(dst, root), 'generated'))
        print('MISMATCH: %s is not the output of utils/mechanism_contract.py' % os.path.relpath(dst, root))
        sys.exit(1)
    print('OK: %s is the output of utils/mechanism_contract.py (%d cases)' % (os.path.relpath(dst, root), len(C['cases'])))
    sys.exit(0)
open(dst, 'w').write(text)
print('written', dst, 'cases', len(C['cases']))
